### ISSUE TITLE
Command "extension.translate" not found

### ISSUE THREAD

**Issue by bellothornus** [pevecyan/vscode-deepl-translator#1]
I installed the extension in visual studio code in my %User%/.vscode/extensions 

but when i launch the command from VSC with ctrl+shift+p and type "deepl" to launch "Translate Deepl" it says that Command "Translate Deepl" resulted in an error (command "extension.translate") not found

**Comment by pevecyan** [comment]
Can you pull down source one more time, put it into that folder and run "npm install" inside of it

**Comment by pevecyan** [comment]
Currently it only translates from english to germa, adjust extension.js:63 to your needs

**Comment by bellothornus** [comment]
Oh, thank you for your fast answer, i didnt know that i have to install it with npm packet manager.
I changed the en ==> de to en ==> es and it worked when i select the text and with ctrl+shift+p and searched "deepl" and execute it it translates the text in its position, i love your vscode extension, but why dont put it in the extension search bar of vscode instead of having to search in github? your code will be more popular!

**Comment by pevecyan** [comment]
Great that it worked for you 👍 I don't want to release it to official extension market place since this is probably not compliant with deepL terms of use as they provide API for translations which is not free.
